// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type Genre struct {
	ID        int32  `json:"id"`
	NameGenre string `json:"name_genre"`
}

type Movie struct {
	ID          int32          `json:"id"`
	Name        string         `json:"name"`
	Author      string         `json:"author"`
	Duration    int32          `json:"duration"`
	Score       sql.NullString `json:"score"`
	Review      sql.NullString `json:"review"`
	Description sql.NullString `json:"description"`
}

type MovieGenre struct {
	MovieID int32 `json:"movie_id"`
	GenreID int32 `json:"genre_id"`
}
