// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const addMovieGenre = `-- name: AddMovieGenre :one
INSERT INTO movie_genre(movie_id,genre_id)
VALUES( $1, $2)
RETURNING movie_id,genre_id
`

type AddMovieGenreParams struct {
	MovieID int32 `json:"movie_id"`
	GenreID int32 `json:"genre_id"`
}

func (q *Queries) AddMovieGenre(ctx context.Context, arg AddMovieGenreParams) (MovieGenre, error) {
	row := q.db.QueryRowContext(ctx, addMovieGenre, arg.MovieID, arg.GenreID)
	var i MovieGenre
	err := row.Scan(&i.MovieID, &i.GenreID)
	return i, err
}

const createGenre = `-- name: CreateGenre :one
INSERT INTO genre(name_genre)
VALUES ($1)
RETURNING id, name_genre
`

func (q *Queries) CreateGenre(ctx context.Context, nameGenre string) (Genre, error) {
	row := q.db.QueryRowContext(ctx, createGenre, nameGenre)
	var i Genre
	err := row.Scan(&i.ID, &i.NameGenre)
	return i, err
}

const createMovie = `-- name: CreateMovie :one
INSERT INTO movie(name, author, duration, score, review, description)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, author, duration, score, review, description
`

type CreateMovieParams struct {
	Name        string         `json:"name"`
	Author      string         `json:"author"`
	Duration    int32          `json:"duration"`
	Score       sql.NullString `json:"score"`
	Review      sql.NullString `json:"review"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) CreateMovie(ctx context.Context, arg CreateMovieParams) (Movie, error) {
	row := q.db.QueryRowContext(ctx, createMovie,
		arg.Name,
		arg.Author,
		arg.Duration,
		arg.Score,
		arg.Review,
		arg.Description,
	)
	var i Movie
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Author,
		&i.Duration,
		&i.Score,
		&i.Review,
		&i.Description,
	)
	return i, err
}

const deleteGenre = `-- name: DeleteGenre :exec
DELETE FROM genre
WHERE id = $1
`

func (q *Queries) DeleteGenre(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteGenre, id)
	return err
}

const deleteMovie = `-- name: DeleteMovie :exec
DELETE FROM movie
WHERE id = $1
`

func (q *Queries) DeleteMovie(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteMovie, id)
	return err
}

const getGenre = `-- name: GetGenre :one
SELECT id, name_genre
FROM genre
WHERE id = $1
`

func (q *Queries) GetGenre(ctx context.Context, id int32) (Genre, error) {
	row := q.db.QueryRowContext(ctx, getGenre, id)
	var i Genre
	err := row.Scan(&i.ID, &i.NameGenre)
	return i, err
}

const getMovie = `-- name: GetMovie :one
SELECT id, name, author, duration, score, review, description
FROM movie
WHERE id = $1
`

func (q *Queries) GetMovie(ctx context.Context, id int32) (Movie, error) {
	row := q.db.QueryRowContext(ctx, getMovie, id)
	var i Movie
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Author,
		&i.Duration,
		&i.Score,
		&i.Review,
		&i.Description,
	)
	return i, err
}

const listGenre = `-- name: ListGenre :many
SELECT id, name_genre
FROM genre
ORDER BY name_genre
`

func (q *Queries) ListGenre(ctx context.Context) ([]Genre, error) {
	rows, err := q.db.QueryContext(ctx, listGenre)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Genre
	for rows.Next() {
		var i Genre
		if err := rows.Scan(&i.ID, &i.NameGenre); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMovie = `-- name: ListMovie :many
SELECT id, name, author, duration, score, review, description
FROM movie m
ORDER BY name
`

func (q *Queries) ListMovie(ctx context.Context) ([]Movie, error) {
	rows, err := q.db.QueryContext(ctx, listMovie)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Movie
	for rows.Next() {
		var i Movie
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Author,
			&i.Duration,
			&i.Score,
			&i.Review,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeMovieGenre = `-- name: RemoveMovieGenre :exec
DELETE FROM movie_genre
WHERE movie_id = $1 AND genre_id = $2
`

type RemoveMovieGenreParams struct {
	MovieID int32 `json:"movie_id"`
	GenreID int32 `json:"genre_id"`
}

func (q *Queries) RemoveMovieGenre(ctx context.Context, arg RemoveMovieGenreParams) error {
	_, err := q.db.ExecContext(ctx, removeMovieGenre, arg.MovieID, arg.GenreID)
	return err
}

const updateGenre = `-- name: UpdateGenre :exec
UPDATE genre
SET name_genre = $2
WHERE id = $1
`

type UpdateGenreParams struct {
	ID        int32  `json:"id"`
	NameGenre string `json:"name_genre"`
}

func (q *Queries) UpdateGenre(ctx context.Context, arg UpdateGenreParams) error {
	_, err := q.db.ExecContext(ctx, updateGenre, arg.ID, arg.NameGenre)
	return err
}

const updateMovie = `-- name: UpdateMovie :exec
UPDATE movie
SET name = $2, author = $3, duration = $4, score = $5, review = $6, description = $7
WHERE id = $1
`

type UpdateMovieParams struct {
	ID          int32          `json:"id"`
	Name        string         `json:"name"`
	Author      string         `json:"author"`
	Duration    int32          `json:"duration"`
	Score       sql.NullString `json:"score"`
	Review      sql.NullString `json:"review"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) UpdateMovie(ctx context.Context, arg UpdateMovieParams) error {
	_, err := q.db.ExecContext(ctx, updateMovie,
		arg.ID,
		arg.Name,
		arg.Author,
		arg.Duration,
		arg.Score,
		arg.Review,
		arg.Description,
	)
	return err
}
